services:
  mongo:
    image: mongo:5
    environment:
        MONGO_INITDB_DATABASE: MsrdProducts
    volumes:
      - mongo-volume:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    restart: always

  mongo-express:
    image: mongo-express
    profiles: 
      - tools
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
    logging:
      options:
        max-size: "12m"
        max-file: "5"
      driver: json-file
      
volumes:
  mongo-volume: